### PR TITLE
Rebase yelp-xsl over 3.31.90

### PR DESCRIPTION
**Pull request by uajain**
All downstream patches are dropped. 

List of commits that were rebased over upstream:
* pick 9bc6f02a Version 3.19.90
  **dropped** as version bump
* pick b9ee65b8 Updated Occitan translation
  **dropped** as outdated translation from upstream
* pick 1c09c676 Updated Occitan translation
  **dropped** as outdated translation from upstream
* pick f05da42c Version 3.20.0
  **dropped** as version bump
* pick 16ebea98 Version 3.20.1
  **dropped** as version bump
* pick a5c13395 Close video player after video finished
 **dropped** as not required anymore.
  (See https://phabricator.endlessm.com/T16828)

https://phabricator.endlessm.com/T25371

### CODE REVIEW

**Comment by uajain** [comment]
retest this please

**Comment by uajain** [comment]
retest this please

**Comment by uajain** [comment]
retest this please

**Review by wjt — COMMENTED** [review]
Even though we don't have any videos in our downstream help center content at the moment, I know there was some desire from Solutions folks to add videos again in future. (Notwithstanding the very good points on T16828 that they are expensive to maintain.)

When that was discussed I found an example in the upstream docs which had a video:

> I've attached a screenshot taken on a computer running Fedora, which has a recent version of upstream GNOME & its documentation. Here's the corresponding source: https://gitlab.gnome.org/GNOME/gnome-getting-started-docs/blob/master/gnome-help/C/getting-started.page#L211-285
>
> Screenshot from 2018-12-11 16-40-38

So I think it would be worth testing how the patch you're proposing to drop affects the behaviour when viewing a video. If it improves it, I suggest keeping it and sending it upstream; if not, sure, we can drop it. (And if this package has no delta compared to Debian as a result, we could consider moving it into eos:master:core and getting rid of this repo.)

**Comment by uajain** [comment]
>I think it would be worth testing how the patch you're proposing to drop affects the behaviour when viewing a video. If it improves it, I suggest keeping it and sending it upstream

I tested the patch on upstream version of `yelp`/`yelp-xsl` and it seems that it has no effect on the desired behavior. Looking at the code and few couple of greps, it seems reasonsable but I cannot see the desired behavior this patch should have. 

We might need to confirm first whether this patch actually worked downstream in previously releases. Building old versions locally seems a bit tedious task as I think it spans across multiple modules to get it right ( and working probably). 
(I tried building previous version of `yelp-xsl/yelp` locally but seems too broken. `XSL stylesheets not found` and what not). After this, I decided not to give it anymore time and suggest we drop the patch.

>(And if this package has no delta compared to Debian as a result, we could consider moving it into eos:master:core and getting rid of this repo.)

Does "getting rid of this repo" will affects solution folks in the future? Maybe need some thinking.

**Comment by wjt** [comment]
> > I think it would be worth testing how the patch you're proposing to drop affects the behaviour when viewing a video. If it improves it, I suggest keeping it and sending it upstream
> 
> I tested the patch on upstream version of `yelp`/`yelp-xsl` and it seems that it has no effect on the desired behavior. Looking at the code and few couple of greps, it seems reasonsable but I cannot see the desired behavior this patch should have.
> 
> We might need to confirm first whether this patch actually worked downstream in previously releases. Building old versions locally seems a bit tedious task as I think it spans across multiple modules to get it right ( and working probably).
> (I tried building previous version of `yelp-xsl/yelp` locally but seems too broken. `XSL stylesheets not found` and what not). After this, I decided not to give it anymore time and suggest we drop the patch.

OK, fine by me.

> > (And if this package has no delta compared to Debian as a result, we could consider moving it into eos:master:core and getting rid of this repo.)
> 
> Does "getting rid of this repo" will affects solution folks in the future? Maybe need some thinking.

I don't see why it would.

Up to you if you want to just push ahead with a no-delta repo here, or migrate it to OBS. I believe https://phabricator.endlessm.com/w/howto/move_a_package_to_obs/ outlines the process.

**Comment by uajain** [comment]
yelp-xsl-3.32 landed in OBS eos:master:core.

**Pull request closed without merging**
